version: "3"
services:
  app:
    env_file:
      - .env
    container_name: employee_app_backend
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - employee_app_database
  employee_app_database:
    image: postgres
    container_name: employee_app_database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/data/postgres
    env_file:
      - .env
  employee_app_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_USERNAME: admin
      PGADMIN_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - employee_app_database

volumes:
  postgres:
    driver: local
